package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Equipment;
import org.mybatis.cdi.Mapper;

@Mapper
public interface EquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EQUIPMENT
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EQUIPMENT
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    int insert(Equipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EQUIPMENT
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    Equipment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EQUIPMENT
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    List<Equipment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.EQUIPMENT
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    int updateByPrimaryKey(Equipment record);


}