package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Training;

public interface TrainingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINING
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINING
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    int insert(Training record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINING
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    Training selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINING
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    List<Training> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TRAINING
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    int updateByPrimaryKey(Training record);
}