package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;
import lt.vu.mybatis.model.Training;

public class Equipment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EQUIPMENT.ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EQUIPMENT.NAME
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.EQUIPMENT.TRAINING_ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    private Integer trainingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EQUIPMENT.ID
     *
     * @return the value of PUBLIC.EQUIPMENT.ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EQUIPMENT.ID
     *
     * @param id the value for PUBLIC.EQUIPMENT.ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EQUIPMENT.NAME
     *
     * @return the value of PUBLIC.EQUIPMENT.NAME
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EQUIPMENT.NAME
     *
     * @param name the value for PUBLIC.EQUIPMENT.NAME
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.EQUIPMENT.TRAINING_ID
     *
     * @return the value of PUBLIC.EQUIPMENT.TRAINING_ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public Integer getTrainingId() {
        return trainingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.EQUIPMENT.TRAINING_ID
     *
     * @param trainingId the value for PUBLIC.EQUIPMENT.TRAINING_ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public void setTrainingId(Integer trainingId) {
        this.trainingId = trainingId;
    }

    @Getter
    @Setter
    private Training training;
}