package lt.vu.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

public class Training {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAINING.ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TRAINING.TRAIN_NAME
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    private String trainName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAINING.ID
     *
     * @return the value of PUBLIC.TRAINING.ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAINING.ID
     *
     * @param id the value for PUBLIC.TRAINING.ID
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TRAINING.TRAIN_NAME
     *
     * @return the value of PUBLIC.TRAINING.TRAIN_NAME
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public String getTrainName() {
        return trainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TRAINING.TRAIN_NAME
     *
     * @param trainName the value for PUBLIC.TRAINING.TRAIN_NAME
     *
     * @mbg.generated Sun Apr 23 20:32:35 EEST 2023
     */
    public void setTrainName(String trainName) {
        this.trainName = trainName;
    }

    @Getter
    @Setter
    private List<Player> players = new ArrayList<>();

    @Getter
    @Setter
    private List<Equipment> equipments = new ArrayList<>();
}